version: "3.9"
services:
  dev:
    build: .
    command: /bin/sh -c "while sleep 1000; do :; done"
    depends_on:
      - db
    ports:
      - "8000:5000"
    volumes:
      - ..:/workspace:cached

  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: 'db'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'password'
    volumes:
      - mysql:/var/lib/mysql

volumes:
  mysql: